export const symbols = {
  trefl: '/src/assets/img/cards/symbol-trefl.png',
  karo: '/src/assets/img/cards/symbol-karo.png',
  kier: '/src/assets/img/cards/symbol-kier.png',
  pik: '/src/assets/img/cards/symbol-pik.png'
};

export const items = [
  { id: 1, name: '2', number: 2, symbol: symbols.trefl },
  { id: 2, name: '2', number: 2, symbol: symbols.karo },
  { id: 3, name: '2', number: 2, symbol: symbols.kier },
  { id: 4, name: '2', number: 2, symbol: symbols.pik },
  { id: 5, name: '3', number: 3, symbol: symbols.trefl },
  { id: 6, name: '3', number: 3, symbol: symbols.karo },
  { id: 7, name: '3', number: 3, symbol: symbols.kier },
  { id: 8, name: '3', number: 3, symbol: symbols.pik },
  { id: 9, name: '4', number: 4, symbol: symbols.trefl },
  { id: 10, name: '4', number: 4, symbol: symbols.karo },
  { id: 11, name: '4', number: 4, symbol: symbols.kier },
  { id: 12, name: '4', number: 4, symbol: symbols.pik },
  { id: 13, name: '5', number: 5, symbol: symbols.trefl },
  { id: 14, name: '5', number: 5, symbol: symbols.karo },
  { id: 15, name: '5', number: 5, symbol: symbols.kier },
  { id: 16, name: '5', number: 5, symbol: symbols.pik },
  { id: 17, name: '6', number: 6, symbol: symbols.trefl },
  { id: 18, name: '6', number: 6, symbol: symbols.karo },
  { id: 19, name: '6', number: 6, symbol: symbols.kier },
  { id: 20, name: '6', number: 6, symbol: symbols.pik },
  { id: 21, name: '7', number: 7, symbol: symbols.trefl },
  { id: 22, name: '7', number: 7, symbol: symbols.karo },
  { id: 23, name: '7', number: 7, symbol: symbols.kier },
  { id: 24, name: '7', number: 7, symbol: symbols.pik },
  { id: 25, name: '8', number: 8, symbol: symbols.trefl },
  { id: 26, name: '8', number: 8, symbol: symbols.karo },
  { id: 27, name: '8', number: 8, symbol: symbols.kier },
  { id: 28, name: '8', number: 8, symbol: symbols.pik },
  { id: 29, name: '9', number: 9, symbol: symbols.trefl },
  { id: 30, name: '9', number: 9, symbol: symbols.karo },
  { id: 31, name: '9', number: 9, symbol: symbols.kier },
  { id: 32, name: '9', number: 9, symbol: symbols.pik },
  { id: 33, name: '10', number: 10, symbol: symbols.trefl },
  { id: 34, name: '10', number: 10, symbol: symbols.karo },
  { id: 35, name: '10', number: 10, symbol: symbols.kier },
  { id: 36, name: '10', number: 10, symbol: symbols.pik },
  { id: 37, name: 'J', number: 10, symbol: symbols.trefl },
  { id: 38, name: 'J', number: 10, symbol: symbols.karo },
  { id: 39, name: 'J', number: 10, symbol: symbols.kier },
  { id: 40, name: 'J', number: 10, symbol: symbols.pik },
  { id: 41, name: 'Q', number: 10, symbol: symbols.trefl },
  { id: 42, name: 'Q', number: 10, symbol: symbols.karo },
  { id: 43, name: 'Q', number: 10, symbol: symbols.kier },
  { id: 44, name: 'Q', number: 10, symbol: symbols.pik },
  { id: 45, name: 'K', number: 10, symbol: symbols.trefl },
  { id: 46, name: 'K', number: 10, symbol: symbols.karo },
  { id: 47, name: 'K', number: 10, symbol: symbols.kier },
  { id: 48, name: 'K', number: 10, symbol: symbols.pik },
  { id: 49, name: 'A', number: 11, symbol: symbols.trefl },
  { id: 50, name: 'A', number: 11, symbol: symbols.karo },
  { id: 51, name: 'A', number: 11, symbol: symbols.kier },
  { id: 52, name: 'A', number: 11, symbol: symbols.pik }
];

